### ISSUE TITLE
9.0.106: `error CS1503: Argument 1: cannot convert from 'System.ReadOnlySpan<char>' to 'string?'`

### ISSUE THREAD

**Issue by eduherminio** [dotnet/sdk#49107]
### Describe the bug
In 9.0.106 for Ubuntu (latest available in .NET backports Ubuntu feed) the provided code doesn't compile.
`error CS1503: Argument 1: cannot convert from 'System.ReadOnlySpan<char>' to 'string?'`

I assume this might have been fixed but not backported to 1xx (haven't found the relevant issue), but looks relevant enough for me to back port

### To Reproduce
```csharp
string str = "test";
ReadOnlySpan<char> readOnlySpan = str;
if (str.Equals(readOnlySpan, StringComparison.OrdinalIgnoreCase))
{
    Console.WriteLine("yay");
}
```

Works in 9.0.300 under Windows

### Further technical details
```bash
~$ dotnet --info
.NET SDK:
 Version:           9.0.106
 Commit:            3d441471e6
 Workload version:  9.0.100-manifests.431e9f8c
 MSBuild version:   17.12.35+3d441471e

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  24.04
 OS Platform: Linux
 RID:         ubuntu.24.04-x64
 Base Path:   /usr/lib/dotnet/sdk/9.0.106/

.NET workloads installed:
There are no installed workloads to display.
Configured to use loose manifests when installing new manifests.

Host:
  Version:      9.0.5
  Architecture: x64
  Commit:       3d441471e6

.NET SDKs installed:
  9.0.106 [/usr/lib/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.5 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.5 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by 333fred** [comment]
Duplicate of https://github.com/dotnet/sdk/issues/49108.
