### PR TITLE
Update azurelinux-3.0 build containers to .NET 10 version

### LINKED ISSUE #4866: AzureLinux verticals are failing
```
    /__w/1/s/src/runtime/src/coreclr/pal/src/thread/process.cpp:2572:16: error: use of undeclared identifier 'MEMBARRIER_CMD_PRIVATE_EXPEDITED'
       2572 |         mask & MEMBARRIER_CMD_PRIVATE_EXPEDITED)
            |                ^
      [ 85%] Building CXX object pal/src/CMakeFiles/coreclrpal.dir/arch/amd64/signalhandlerhelper.cpp.o
      /__w/1/s/src/runtime/src/coreclr/pal/src/thread/process.cpp:2575:24: error: use of undeclared identifier 'MEMBARRIER_CMD_REGISTER_PRIVATE_EXPEDITED'
       2575 |         if (membarrier(MEMBARRIER_CMD_REGISTER_PRIVATE_EXPEDITED, 0, 0) == 0)
            |                        ^
      [ 85%] Built target eventing_headers
      /__w/1/s/src/runtime/src/coreclr/pal/src/thread/process.cpp:2640:33: error: use of undeclared identifier 'MEMBARRIER_CMD_PRIVATE_EXPEDITED'
       2640 |         int status = membarrier(MEMBARRIER_CMD_PRIVATE_EXPEDITED, 0, 0);
            |                                 ^
      3 errors generated.
      make[3]: *** [pal/src/CMakeFiles/coreclrpal.dir/build.make:944: pal/src/CMakeFiles/coreclrpal.dir/thread/process.cpp.o] Error 1
      make[3]: *** Waiting for unfinished jobs....

```

Maybe regressed with https://github.com/dotnet/sdk/commit/affada6e1e99189c71777602c6764b1e8d61b8b1?

### PR DESCRIPTION
**Pull request by jkotas**
Fixes https://github.com/dotnet/source-build/issues/4866

### CODE REVIEW

**Comment by jkotas** [comment]
Update to containers used by dotnet/runtime main

**Review by ViktorHofer — APPROVED** [review]

**Comment by ViktorHofer** [comment]
```
Error response from daemon: manifest for mcr.microsoft.com/dotnet-buildtools/prereqs:azurelinux-3.0-net10.0-android-openssl-amd64 not found: manifest unknown: manifest tagged by "azurelinux-3.0-net10.0-android-openssl-amd64" is not found
##[warning]Docker pull failed with exit code 1, back off 00:00:10 seconds before retry.
/usr/bin/docker pull mcr.microsoft.com/dotnet-buildtools/prereqs:azurelinux-3.0-net10.0-android-openssl-amd64
Error response from daemon: manifest for mcr.microsoft.com/dotnet-buildtools/prereqs:azurelinux-3.0-net10.0-android-openssl-amd64 not found: manifest unknown: manifest tagged by "azurelinux-3.0-net10.0-android-openssl-amd64" is not found
##[warning]Docker pull failed with exit code 1, back off 00:00:10 seconds before retry.
/usr/bin/docker pull mcr.microsoft.com/dotnet-buildtools/prereqs:azurelinux-3.0-net10.0-android-openssl-amd64
Error response from daemon: manifest for mcr.microsoft.com/dotnet-buildtools/prereqs:azurelinux-3.0-net10.0-android-openssl-amd64 not found: manifest unknown: manifest tagged by "azurelinux-3.0-net10.0-android-openssl-amd64" is not found
```

@jkotas

File: eng/pipelines/templates/variables/vmr-build.yml [hunk 1]
```diff
@@ -92,52 +92,52 @@ variables:
...
   value: androidCrossContainer
 - name: androidCrossContainerImage
-  value: mcr.microsoft.com/dotnet-buildtools/prereqs:azurelinux-3.0-net9.0-cross-android-amd64
+  value: mcr.microsoft.com/dotnet-buildtools/prereqs:azurelinux-3.0-net10.0-cross-android-amd64
 
 - name: linuxBionicCrossContainerName
   value: linuxBionicCrossContainer
 - name: linuxBionicCrossContainerImage
-  value: mcr.microsoft.com/dotnet-buildtools/prereqs:azurelinux-3.0-net9.0-android-openssl
+  value: mcr.microsoft.com/dotnet-buildtools/prereqs:azurelinux-3.0-net10.0-android-openssl-amd64
```
Comment (ViktorHofer) [inline eng/pipelines/templates/variables/vmr-build.yml:130]:
```suggestion
  value: mcr.microsoft.com/dotnet-buildtools/prereqs:azurelinux-3.0-net10.0-android-openssl
```

**Review by akoeplinger — APPROVED** [review]

File: eng/pipelines/templates/variables/vmr-build.yml [hunk 2]
```diff
@@ -92,52 +92,52 @@ variables:
...
   value: androidCrossContainer
 - name: androidCrossContainerImage
-  value: mcr.microsoft.com/dotnet-buildtools/prereqs:azurelinux-3.0-net9.0-cross-android-amd64
+  value: mcr.microsoft.com/dotnet-buildtools/prereqs:azurelinux-3.0-net10.0-cross-android-amd64
 
 - name: linuxBionicCrossContainerName
   value: linuxBionicCrossContainer
 - name: linuxBionicCrossContainerImage
-  value: mcr.microsoft.com/dotnet-buildtools/prereqs:azurelinux-3.0-net9.0-android-openssl
+  value: mcr.microsoft.com/dotnet-buildtools/prereqs:azurelinux-3.0-net10.0-android-openssl
```
Comment (akoeplinger) [inline eng/pipelines/templates/variables/vmr-build.yml:130]:
```suggestion
  value: mcr.microsoft.com/dotnet-buildtools/prereqs:azurelinux-3.0-net10.0-android-openssl-amd64
```

**Review by jkoritzinsky — APPROVED** [review]

**Comment by am11** [comment]
We should keep the fallback removed in https://github.com/dotnet/runtime/pull/111943 as this will likely hit non-MSFT builds:

```c
#ifndef MEMBARRIER_CMD_QUERY
#define MEMBARRIER_CMD_QUERY 0
#endif

#ifndef MEMBARRIER_CMD_PRIVATE_EXPEDITED
#define MEMBARRIER_CMD_PRIVATE_EXPEDITED (1 << 3)
#endif 
```

cc @dotnet/distro-maintainers

**Comment by ViktorHofer** [comment]
@akoeplinger `mcr.microsoft.com/dotnet-buildtools/prereqs:azurelinux-3.0-net10.0-android-openssl-amd64` doesn't seem to exist which is why I changed it to `mcr.microsoft.com/dotnet-buildtools/prereqs:azurelinux-3.0-net10.0-android-openssl`

**Comment by akoeplinger** [comment]
Yeah I messed up correcting the image name, should be fixed now

**Comment by jkotas** [comment]
> We should keep the fallback removed in https://github.com/dotnet/runtime/pull/111943 as this will likely hit non-MSFT builds

It can be hit on distro/kernel versions that are older than Ubuntu 18.04 (2018). Is anybody going to build .NET 10 on these ancient distros?
