### PR TITLE
Extend build server shutdown tracing

### PR DESCRIPTION
**Pull request by jjonescz**
The output might look something like this:

```log
❯ & "D:\sdk-3\.dotnet\dotnet.exe" exec D:\sdk-3\artifacts\bin\dotnet\Debug\net10.0\dotnet.dll build-server shutdown --vbcscompiler
Telemetry is: Disabled
Shutting down VB/C# compiler server...
Running D:\sdk-3\.dotnet\dotnet.exe exec D:\sdk-3\artifacts\bin\dotnet\Debug\net10.0\Roslyn\bincore\VBCSCompiler.dll -shutdown
> D:\sdk-3\.dotnet\dotnet.exe exec D:\sdk-3\artifacts\bin\dotnet\Debug\net10.0\Roslyn\bincore\VBCSCompiler.dll -shutdown
Process ID: 43340
< D:\sdk-3\.dotnet\dotnet.exe exec D:\sdk-3\artifacts\bin\dotnet\Debug\net10.0\Roslyn\bincore\VBCSCompiler.dll -shutdown exited with -2147450751 in 21 ms.
Shutting down 'microsoft.net.sdk.compilers.toolset' compilers.
Enumerating 'C:\.tools\.nuget\packages\microsoft.net.sdk.compilers.toolset'.
Found 'C:\.tools\.nuget\packages\microsoft.net.sdk.compilers.toolset\9.0.100-preview.7.24365.12\VBCSCompiler.exe'.
Running C:\.tools\.nuget\packages\microsoft.net.sdk.compilers.toolset\9.0.100-preview.7.24365.12\VBCSCompiler.exe -shutdown
> C:\.tools\.nuget\packages\microsoft.net.sdk.compilers.toolset\9.0.100-preview.7.24365.12\VBCSCompiler.exe -shutdown
Process ID: 22744
< C:\.tools\.nuget\packages\microsoft.net.sdk.compilers.toolset\9.0.100-preview.7.24365.12\VBCSCompiler.exe -shutdown exited with 0 in 112 ms.
Found 'C:\.tools\.nuget\packages\microsoft.net.sdk.compilers.toolset\9.0.101\VBCSCompiler.exe'.
Running C:\.tools\.nuget\packages\microsoft.net.sdk.compilers.toolset\9.0.101\VBCSCompiler.exe -shutdown
> C:\.tools\.nuget\packages\microsoft.net.sdk.compilers.toolset\9.0.101\VBCSCompiler.exe -shutdown
Process ID: 23660
< C:\.tools\.nuget\packages\microsoft.net.sdk.compilers.toolset\9.0.101\VBCSCompiler.exe -shutdown exited with 0 in 113 ms.
```

### CODE REVIEW

**Review by ellahathaway — APPROVED** [review]
Thank you!

**Comment by ellahathaway** [comment]
Related to https://github.com/dotnet/source-build/issues/4796

**Review by jaredpar — APPROVED** [review]

**Review by baronfel — APPROVED** [review]

**Comment by baronfel** [comment]
The arm64 failures on macOS have been pretty persistent - @marcpopMSFT mind merging this on red to get better diagnosis?

**Comment by ViktorHofer** [comment]
This broke the build :( Raced with https://github.com/dotnet/sdk/commit/b09e142523221363fb31ee3fcaf1f5dae68150b1

> src/Cli/Microsoft.DotNet.Cli.Utils/Command.cs(44,28): error CS8600: (NETCORE_ENGINEERING_TELEMETRY=Build) Converting null literal or possible null value to non-nullable type.

**Comment by v-wuzhai** [comment]
@jaredpar I tried to resolve the build failure, but it seems there are still other issues. Could you take a look at #45411?
