### ISSUE TITLE
MSB3270 warnings for .NET Framework test project that depends on an ASP.NET Core web site

### ISSUE THREAD

**Issue by dougbu** [dotnet/sdk#926]
Get an MSB3270 warning when a test project depends on an ASP.NET Core web site and both target .NET 4.5.2. But the warning shows up _only_ when building with `msbuild` or (equivalently) in Visual Studio.

Not sure which of `msbuild` or `dotnet build` is doing the **Right Thing:tm:**. Either way, this feels like fallout from #396 fix. (I lean toward thinking `dotnet build` is in the right here.)

### Repro
1. `git clone https://github.com/dougbu/WebSiteDependencyTest.git`
2. `dotnet restore`
3. `dotnet build .\WebSiteDependencyTest.sln`
4. `msbuild .\WebSiteDependencyTest.sln /verbosity:minimal`

#### Expected
Step 4 should produce no warnings, matching the output of step 3.

#### Actual
```
  WebSiteDependencyTest -> C:\dd\Projects\WebSiteDependencyTest\WebSiteDependencyTest\bin\Debug\net452\WebSiteDependencyTest.exe
C:\Program Files (x86)\Microsoft Visual Studio\2017\INT\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "C:\dd\Projects\WebSiteDependencyTest\WebSiteDependencyTest\bin\Debug\net452\WebSiteDependencyTest.exe", "x86". This mismatch may cause runtime failures. Please consider changing the targeted process or architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project. [C:\dd\Projects\WebSiteDependencyTest\XUnitTest\XUnitTest.csproj]
  XUnitTest -> C:\dd\Projects\WebSiteDependencyTest\XUnitTest\bin\Debug\net452\XUnitTest.dll
```

### Workaround
Warnings go away after adding `<OutputType>EXE</OutputType>` to the `XUnitTest` project. That's not particularly discoverable 😈 

### Side note
Excellent to see the more modern `dotnet build` defaults to `/verbosity:minimal`!

**Comment by nguerrera** [comment]
I think the warning is accurate though I'm not sure why it is only shows in full msbuild. The web app has been stamped x86 because it pulls in native dependencies. The referencing project therefore should be marked x86 too. Setting OutputType exe for the unit test project causes it to let the RID inference for it to kick in too. 

Fixing https://github.com/dotnet/sdk/issues/909 would also fix this scenario where the project referencing the exe is a test project. I think that is probably sufficient since it is strange to reference to an app from a genuine library. In that case, the user would still has to make the library platform-specific manually, but I think that's acceptable.

**Comment by dougbu** [comment]
> The referencing project therefore should be marked x86 too.

What is the correct way to do this? Setting `$(OutputType)` seems wrong for a test library. I tried a couple of things but the properties I set were ignored (because it wasn't an executable) or caused compilation errors (as if MSIL packages the tests pulled in weren't referenced).

> Fixing #909 would also fix this scenario where the project referencing the exe is a test project.

I agree and am somewhat surprised builds fail in the #909 scenario but only hit a warning here.

**Comment by nguerrera** [comment]
You could set PlatformTarget to x86 in the test project or RuntimeIdentifier=win7-x86. Do you have a repro for the compilation errors?

**Comment by nguerrera** [comment]
#909 scenario doesn't fail the build, it fails at runtime. :(

**Comment by dougbu** [comment]
> Do you have a repro for the compilation errors?

I don't remember if I've seen this w/ https://github.com/dougbu/WebSiteDependencyTest. But, it definitely happened in the MVC repo.

I can't reproduce the issue now; no build problems with either `$(PlatformTarget)` or `$(RuntimeIdentifier)` set. I probably let things get out of sync and ending up building without current dependencies or some such. Or, my setup just had a transient issue that's cleared itself.

**Comment by livarcocc** [comment]
Let's track this fix in #909. Re-activate if I got this wrong and we need this issue.
