### ISSUE TITLE
9.0.106: error CS0121: ambiguous call between `MemoryExtensions.CopyTo`: `Span` and `Memory`

### ISSUE THREAD

**Issue by eduherminio** [dotnet/sdk#49108]
### Describe the bug
In 9.0.106 for Ubuntu (latest available in .NET backports Ubuntu feed) the provided code doesn't compile with the following error:
`error CS0121: The call is ambiguous between the following methods or properties: 'MemoryExtensions.CopyTo<T>(T[]?, Memory<T>)' and 'MemoryExtensions.CopyTo<T>(T[]?, Span<T>)'`

I assume this might have been fixed but not backported to 1xx (haven't found the relevant issue).
I assume this might have been fixed but not backported to 1xx (haven't found the relevant issue), but it might be relevant enough to be backported.

### To Reproduce
```
private static int[] CopyToImpl(int[] array)
{
    var result = new int[array.Length];
    array.CopyTo(result);

    return result;
}
```

Works in 9.0.300 under Windows

### Further technical details
```bash
~$ dotnet --info
.NET SDK:
 Version:           9.0.106
 Commit:            3d441471e6
 Workload version:  9.0.100-manifests.431e9f8c
 MSBuild version:   17.12.35+3d441471e

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  24.04
 OS Platform: Linux
 RID:         ubuntu.24.04-x64
 Base Path:   /usr/lib/dotnet/sdk/9.0.106/

.NET workloads installed:
There are no installed workloads to display.
Configured to use loose manifests when installing new manifests.

Host:
  Version:      9.0.5
  Architecture: x64
  Commit:       3d441471e6

.NET SDKs installed:
  9.0.106 [/usr/lib/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.5 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.5 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by baronfel** [comment]
@jaredpar is there some overload resolution thing that we introduced/missed backporting?

**Comment by jaredpar** [comment]
> Works in 9.0.300 under Windows

This fails in 9.0.300 for me using your sample code. I used a global.json to pin to 9.0.300 and still get the same error. 

Can you try doing the same and check if you get the same error? 

@333fred, @RikkiGibson

**Comment by RikkiGibson** [comment]
> This should not impact the issue as we haven't tied lang version to TFM yet.

It seems like it could because it might affect whether an API which resolves the ambiguity is present.

**Comment by RikkiGibson** [comment]
I also repro this by simply doing `dotnet new console -o repro;`, pasting the repro code into a class, and `dotnet build`ing (or just waiting for the editor to spin up and report it). I'm using `10.0.100-preview.4.25204.5`.

**Comment by eduherminio** [comment]
> Also in the windows example can you check to see if the project file has `<LangVersion>preview</LangVersion>`.

In my case yes it has it, at `Directory.Build.props` level.
It's [this repo](https://github.com/lynx-chess/Lynx) the one I found the issue with, more specifically [this piece of benchmark code](https://github.com/lynx-chess/Lynx/blob/main/src/Lynx.Benchmark/ArrayCopy_Benchmark.cs#L310)

**Comment by eduherminio** [comment]
> To clarify: the reason I asked about `<LangVersion>preview</LangVersion>` is that it will enable the .NET 10 feature of [first class spans](https://github.com/dotnet/csharplang/issues/7905). That feature will fix ambiguities like the one described in this bug. That feature was not included in 9.0.100 but was included in 9.0.200 and later. I strongly suspect that the repro has this setting in the project file as it explains the symptoms.
> 
> In that case the bug is essentially "Won't Fix" because this is .NET 10 preview behavior. There is no guarantee of it working in .NET 9 SDKs.

This other issue might have the same root cause in that case
https://github.com/dotnet/sdk/issues/49107
