### ISSUE TITLE
Cannot convert from void to IEnumerable<byte> on SDK 9.0.200

### ISSUE THREAD

**Issue by schotime** [dotnet/sdk#46801]
### Describe the bug
After upgrading to 9.0.200 from 9.0.100, the following compilation error occurred.

Argument 1: cannot convert from 'void' to 'System.Collections.Generic.IEnumerable<byte>'

### To Reproduce
```cs
var list = new List<byte>();
var b = new byte[2];
list.AddRange(b.Reverse());
```

**Comment by huoyaoyuan** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/111532 and https://github.com/dotnet/runtime/issues/112540 .

In short, using `preview` language version with .NET 9- will be impacted.
