### ISSUE TITLE
`dotnet test` CLI command doesn't work with multi-targeting projects

### ISSUE THREAD

**Issue by acple** [dotnet/sdk#14168]
**Since rc.1**, when the test target is a multi target framework project, `dotnet test` cli command fails in a build step.

## Repro

[my repro repsitory](https://github.com/acple/SdkRc1Problem)

1. Create test target and unittest project

```csproj
<!--ClassLibrary1/ClassLibrary1.csproj-->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!--Use Multiple Target-->
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
  </PropertyGroup>

</Project>
```

```csharp
namespace ClassLibrary1
{
    public class Class1
    { }
}
```

```csproj
<!--UnitTest/UnitTest.csproj-->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.7.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.1.1" />
    <PackageReference Include="MSTest.TestFramework" Version="2.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../ClassLibrary1/ClassLibrary1.csproj" />
  </ItemGroup>

</Project>
```

```csharp
[TestMethod]
public void Test1()
{
    _ = new Class1();
}
```

2. Add both projects into .sln

```console
$ dotnet new sln
$ dotnet sln add ClassLibrary1
$ dotnet sln add UnitTest
```

3. Run `dotnet test` **for .sln**

```console
$ dotnet test
```

4. It fails while compiling

> /UnitTest/UnitTest1.cs(1,7): error CS0246: The type or namespace name 'ClassLibrary1' could not be found (are you missing a using directive or an assembly reference?) [/UnitTest/UnitTest.csproj]

### 1. Use `--no-build` option to skip build step

`dotnet build && dotnet test --no-build`

### 2. Specify unittest target framework explicitly
`dotnet test -f net5.0`

### 3. Run test for .csproj instead of .sln
`dotnet test UnitTest`

---

This was working correctly until .NET 5 SDK preview.8.

**Comment by rynowak** [comment]
I've run into this issue as well. I was adding .NET 5 testing to our matrix at https://github.com/dapr/dotnet-sdk/ and `dotnet test` no longer works (similar kinds of errors)

**Comment by AndrewTriesToCode** [comment]
Also seeing this on my project as well.
https://github.com/Finbuckle/Finbuckle.MultiTenant/tree/chore/dotnet-core-5.0

If I run separate `dotnet test -f` for each target it works individually.

**Comment by acple** [comment]
I found this seems to be fixed in latest stable version of .NET 5 SDK (in [Docker Hub](https://hub.docker.com/_/microsoft-dotnet-sdk/))
This issue can be closed now.
