### ISSUE TITLE
Dotnet 7.0.201 broke build working in Dotnet 7.0.101

### ISSUE THREAD

**Issue by Xorpio** [dotnet/sdk#30990]
### Describe the bug
Code complied with dotnet 7.0.101 does not build with dotnet 7.0.201

### To Reproduce
If needed i can supply a sample repository.

### Further technical details
When building in azure pipeline with the  dotnet version 7.0.201 i get the error:
```
##[error]/home/vsts/work/1/s/src/Frontend.Admin/Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator/Pages_Veterinarian_List_razor.g.cs(267,146): Error CS1503: Argument 3: cannot convert from 'Microsoft.AspNetCore.Components.EventCallback<string>' to 'System.Action<string?>'
```

This works fine in dotnet version 7.0.101.

**Comment by danroth27** [comment]
We think you might be hitting https://github.com/dotnet/razor/issues/8315. Please update to the latest .NET 7 SDK version (7,.0.202) and see if it resolves your issue.

**Comment by vrushalivartak** [comment]
@Xorpio @danroth27 
This is duplicate of https://github.com/dotnet/razor/issues/8315. Can be closed.

**Comment by Xorpio** [comment]
Yes. Can be closed.
