### PR TITLE
Adding condition for defining Repository Assembly Attributes

### LINKED ISSUE #11862: Don't reference AssemblyMetadataAttribute in generated AssemblyInfo.cs when targeting net40
The ef6 build targeting net40 failed recently with the following error after updating the .NET SDK to 5.0.100-preview.6.20266.3.

```
##[error]artifacts\obj\ef6\Release\net40\ef6.AssemblyInfo.cs(21,30): error CS0234: (NETCORE_ENGINEERING_TELEMETRY=Build) The type or namespace name 'AssemblyMetadataAttribute' does not exist in the namespace 'System.Reflection' (are you missing an assembly reference?)
```

https://github.com/dotnet/ef6/pull/1678

AssemblyMetadataAttribute doesn't exist in net40. ef6 has an AssemblyMetadataAttribute  polyfill in some of its projects, but not the one that failed to build. Adding the polyfil works around the issue.

It looks like this is a regression introduced by https://github.com/dotnet/sdk/pull/11559 and could be fixed by not generating a reference to AssemblyMetadataAttribute when targeting net40.

### PR DESCRIPTION
**Pull request by sfoslund**
Fixes #11862

### CODE REVIEW

File: src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.GenerateAssemblyInfo.targets [hunk 1]
```diff
@@ -32,6 +32,7 @@ Copyright (c) .NET Foundation. All rights reserved.
     <GenerateAssemblyProductAttribute Condition="'$(GenerateAssemblyProductAttribute)' == ''">true</GenerateAssemblyProductAttribute>
     <GenerateAssemblyTitleAttribute Condition="'$(GenerateAssemblyTitleAttribute)' == ''">true</GenerateAssemblyTitleAttribute>
     <GenerateAssemblyVersionAttribute Condition="'$(GenerateAssemblyVersionAttribute)' == ''">true</GenerateAssemblyVersionAttribute>
+    <GenerateAssemblyMetadataAttribute Condition="'$(GenerateAssemblyMetadataAttribute)' == '' and !('$(TargetFrameworkIdentifier)' == '.NETFramework' and $([MSBuild]::VersionLessThan($(TargetFrameworkVersion), 4.5)))">true</GenerateAssemblyMetadataAttribute>
```
Comment (dsplaisted) [inline src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.GenerateAssemblyInfo.targets:35]: Rename this to a less generic name.  We are using the generic `AssemblyMetadataAttribute` to store a specific piece of data (the repository URL).

I thingk `GenerateRepositoryUrlAttribute` is probably a good name.

File: src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToControlGeneratedAssemblyInfo.cs [hunk 2]
```diff
@@ -628,5 +628,33 @@ public void It_includes_repository_url(bool privateRepo)
...
+            var testAsset = _testAssetsManager.CreateTestProject(testProject);
+
+            var buildCommand = new BuildCommand(Log, Path.Combine(testAsset.TestRoot, testProject.Name));
+            buildCommand.Execute()
+                .Should()
+                .Pass();
+
+            var assemblyPath = Path.Combine(buildCommand.GetOutputDirectory(targetFramework).FullName, testProject.Name + ".dll");
+
+            AssemblyInfo.Get(assemblyPath).ContainsKey("AssemblyMetadataAttribute").Should().Be(containsAttribute);
```
Comment (dsplaisted) [inline src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToControlGeneratedAssemblyInfo.cs:657]: It would be better to check that there is an `AssemblyMetadataAttribute` with the expected `Key` and `Value`.

**Review by dsplaisted — APPROVED** [review]
