### ISSUE TITLE
ProduceOnlyReferenceAssembly=true fails with `Do not use refout when using refonly`

### ISSUE THREAD

**Issue by dotMorten** [dotnet/sdk#16910]
The following project fails to compile:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <ProduceOnlyReferenceAssembly>true</ProduceOnlyReferenceAssembly>
  </PropertyGroup>

</Project>
```
The above project will fail to compile with error
> CSC : error CS8308: Do not use refout when using refonly.

This used to work with target `netstandard2.0` instead.

The workaround is to set the following to false:

```xml
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
```

However it's rather counter-intuitive that to generate a reference assembly - but __only__ a reference assembly - you actually have to turn off producing a reference assembly.

It is likely related to this bit and explains why netstandard2.0 works but net5.0+ doesn't:
https://github.com/dotnet/sdk/blob/a30e465a2e2ea4e2550f319a2dc088daaafe5649/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.TargetFrameworkInference.targets#L233

**Comment by tannergooding** [comment]
For reference, from the twitter thread, this was added in .NET 5: https://github.com/dotnet/sdk/blob/a30e465a2e2ea4e2550f319a2dc088daaafe5649/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.TargetFrameworkInference.targets#L233

The compiler treats `refout` and `refonly` as exclusive, so I expect this could be fixed by adding `and ('$(ProduceOnlyReferenceAssembly)' == '' or '$(ProduceOnlyReferenceAssembly)' == 'false')` (or something similar)

**Comment by tannergooding** [comment]
https://github.com/dotnet/roslyn/blob/main/docs/features/refout.md is the Roslyn doc on the feature, which covers the switches being exclusive

**Comment by dotMorten** [comment]
@tannergooding Thanks for the doc. The doc specifies:
> ProduceOnlyReferenceAssembly (boolean) controls whether to pass /refonly to the compiler. It requires opt-in. Cannot be used in conjunction with ProduceReferenceAssembly

Technically I'm not using it in conjunction. I'm only specifying one of them. Something else in the build system now decided to specify the other one.

**Comment by tannergooding** [comment]
> Something else in the build system now decided to specify the other one.

Right, the SDK added a new option specifying it by default for .NET 5+ (it's the `Microsoft.NET.TargetFrameworkInference.targets` I linked a couple posts up).

**Comment by rainersigwald** [comment]
This seems reasonable. Any objection from the compiler side @jcouv?

**Comment by jcouv** [comment]
Sounds like a good idea. I don't see any impact on the compiler and this would make it easier to deal with the implicit default from the SDK.
