### ISSUE TITLE
Recent System.CommandLine upgrade broke source-build in 6.0.2xx

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/sdk#22640]
[This change](https://github.com/dotnet/sdk/commit/0985c0cfab5de33149bb87cd782a0f7e846c0048#diff-2f70e6b441f7ffb00180be1e2832e21e98528943a3648b7fc3256e6d403500ae) to upgrade the System.CommandLine version broke source-build.  The change involved updating the SystemCommandLineVersion property in Versions.props but not updating the Version.Details.xml which specifies the repo's commit sha.  It makes the sdk repo incoherent in a way.  Source-build builds the System.CommandLine api commit specified in the Versions.Details.xml and uses it's version when building the sdk.

The upgraded version (2.0.0-beta1.21504.1) contains new apis that aren't in the version source-build uses.

```
  /repos/tarball3/src/sdk.af3b7d0f15282afee493e61c10b0bb170317de8d/artifacts/source-build/self/src/src/BuiltInTools/dotnet-watch/Program.cs(155,59): error CS1061: 'ParseResult' does not contain a definition for 'GetValueForOption' and no accessible extension method 'GetValueForOption' accepting a first argument of type 'ParseResult' could be found (are you missing a using directive or an assembly reference?) [/repos/tarball3/src/sdk.af3b7d0f15282afee493e61c10b0bb170317de8d/artifacts/source-build/self/src/src/BuiltInTools/dotnet-watch/dotnet-watch.csproj]
  /repos/tarball3/src/sdk.af3b7d0f15282afee493e61c10b0bb170317de8d/artifacts/source-build/self/src/src/Cli/dotnet/CommandLineValidation/CommandLineValidationMessages.cs(13,59): error CS0246: The type or namespace name 'LocalizationResources' could not be found (are you missing a using directive or an assembly reference?) [/repos/tarball3/src/sdk.af3b7d0f15282afee493e61c10b0bb170317de8d/artifacts/source-build/self/src/src/Cli/dotnet/dotnet.csproj]
  /repos/tarball3/src/sdk.af3b7d0f15282afee493e61c10b0bb170317de8d/artifacts/source-build/self/src/src/Cli/dotnet/CommandLineValidation/CommandLineValidationMessages.cs(15,32): error CS0115: 'CommandLineValidationMessages.ExpectsOneArgument(SymbolResult)': no suitable method found to override [/repos/tarball3/src/sdk.af3b7d0f15282afee493e61c10b0bb170317de8d/artifacts/source-build/self/src/src/Cli/dotnet/dotnet.csproj]
  /repos/tarball3/src/sdk.af3b7d0f15282afee493e61c10b0bb170317de8d/artifacts/source-build/self/src/src/Cli/dotnet/CommandLineValidation/CommandLineValidationMessages.cs(20,32): error CS0115: 'CommandLineValidationMessages.NoArgumentProvided(SymbolResult)': no suitable method found to override [/repos/tarball3/src/sdk.af3b7d0f15282afee493e61c10b0bb170317de8d/artifacts/source-build/self/src/src/Cli/dotnet/dotnet.csproj]
  /repos/tarball3/src/sdk.af3b7d0f15282afee493e61c10b0bb170317de8d/artifacts/source-build/self/src/src/Cli/dotnet/CommandLineValidation/CommandLineValidationMessages.cs(25,32): error CS0115: 'CommandLineValidationMessages.FileDoesNotExist(string)': no suitable method found to override [/repos/tarball3/src/sdk.af3b7d0f15282afee493e61c10b0bb170317de8d/artifacts/source-build/self/src/src/Cli/dotnet/dotnet.csproj]
  /repos/tarball3/src/sdk.af3b7d0f15282afee493e61c10b0bb170317de8d/artifacts/source-build/self/src/src/Cli/dotnet/CommandLineValidation/CommandLineValidationMessages.cs(28,32): error CS0115: 'CommandLineValidationMessages.RequiredCommandWasNotProvided()': no suitable method found to override [/repos/tarball3/src/sdk.af3b7d0f15282afee493e61c10b0bb170317de8d/artifacts/source-build/self/src/src/Cli/dotnet/dotnet.csproj]
  /repos/tarball3/src/sdk.af3b7d0f15282afee493e61c10b0bb170317de8d/artifacts/source-build/self/src/src/Cli/dotnet/CommandLineValidation/CommandLineValidationMessages.cs(31,32): error CS0115: 'CommandLineValidationMessages.UnrecognizedArgument(string, IReadOnlyCollection<string>)': no suitable method found to override [/repos/tarball3/src/sdk.af3b7d0f15282afee493e61c10b0bb170317de8d/artifacts/source-build/self/src/src/Cli/dotnet/dotnet.csproj]
  /repos/tarball3/src/sdk.af3b7d0f15282afee493e61c10b0bb170317de8d/artifacts/source-build/self/src/src/Cli/dotnet/CommandLineValidation/CommandLineValidationMessages.cs(34,32): error CS0115: 'CommandLineValidationMessages.UnrecognizedCommandOrArgument(string)': no suitable method found to override [/repos/tarball3/src/sdk.af3b7d0f15282afee493e61c10b0bb170317de8d/artifacts/source-build/self/src/src/Cli/dotnet/dotnet.csproj]
  /repos/tarball3/src/sdk.af3b7d0f15282afee493e61c10b0bb170317de8d/artifacts/source-build/self/src/src/Cli/dotnet/CommandLineValidation/CommandLineValidationMessages.cs(37,32): error CS0115: 'CommandLineValidationMessages.ExpectsFewerArguments(Token, int, int)': no suitable method found to override [/repos/tarball3/src/sdk.af3b7d0f15282afee493e61c10b0bb170317de8d/artifacts/source-build/self/src/src/Cli/dotnet/dotnet.csproj]
  /repos/tarball3/src/sdk.af3b7d0f15282afee493e61c10b0bb170317de8d/artifacts/source-build/self/src/src/Cli/dotnet/CommandLineValidation/CommandLineValidationMessages.cs(45,32): error CS0115: 'CommandLineValidationMessages.DirectoryDoesNotExist(string)': no suitable method found to override [/repos/tarball3/src/sdk.af3b7d0f15282afee493e61c10b0bb170317de8d/artifacts/source-build/self/src/src/Cli/dotnet/dotnet.csproj]
  /repos/tarball3/src/sdk.af3b7d0f15282afee493e61c10b0bb170317de8d/artifacts/source-build/self/src/src/Cli/dotnet/CommandLineValidation/CommandLineValidationMessages.cs(48,32): error CS0115: 'CommandLineValidationMessages.FileOrDirectoryDoesNotExist(string)': no suitable method found to override [/repos/tarball3/src/sdk.af3b7d0f15282afee493e61c10b0bb170317de8d/artifacts/source-build/self/src/src/Cli/dotnet/dotnet.csproj]
  /repos/tarball3/src/sdk.af3b7d0f15282afee493e61c10b0bb170317de8d/artifacts/source-build/self/src/src/Cli/dotnet/CommandLineValidation/CommandLineValidationMessages.cs(51,32): error CS0115: 'CommandLineValidationMessages.InvalidCharactersInPath(char)': no suitable method found to override [/repos/tarball3/src/sdk.af3b7d0f15282afee493e61c10b0bb170317de8d/artifacts/source-build/self/src/src/Cli/dotnet/dotnet.csproj]
  /repos/tarball3/src/sdk.af3b7d0f15282afee493e61c10b0bb170317de8d/artifacts/source-build/self/src/src/Cli/dotnet/CommandLineValidation/CommandLineValidationMessages.cs(54,32): error CS0115: 'CommandLineValidationMessages.RequiredArgumentMissing(SymbolResult)': no suitable method found to override [/repos/tarball3/src/sdk.af3b7d0f15282afee493e61c10b0bb170317de8d/artifacts/source-build/self/src/src/Cli/dotnet/dotnet.csproj]
  /repos/tarball3/src/sdk.af3b7d0f15282afee493e61c10b0bb170317de8d/artifacts/source-build/self/src/src/Cli/dotnet/CommandLineValidation/CommandLineValidationMessages.cs(59,32): error CS0115: 'CommandLineValidationMessages.ResponseFileNotFound(string)': no suitable method found to override [/repos/tarball3/src/sdk.af3b7d0f15282afee493e61c10b0bb170317de8d/artifacts/source-build/self/src/src/Cli/dotnet/dotnet.csproj]
  /repos/tarball3/src/sdk.af3b7d0f15282afee493e61c10b0bb170317de8d/artifacts/source-build/self/src/src/Cli/dotnet/CommandLineValidation/CommandLineValidationMessages.cs(62,32): error CS0115: 'CommandLineValidationMessages.ErrorReadingResponseFile(string, IOException)': no suitable method found to override [/repos/tarball3/src/sdk.af3b7d0f15282afee493e61c10b0bb170317de8d/artifacts/source-build/self/src/src/Cli/dotnet/dotnet.csproj]
  /repos/tarball3/src/sdk.af3b7d0f15282afee493e61c10b0bb170317de8d/artifacts/source-build/self/src/src/Cli/dotnet/CommandLineValidation/CommandLineValidationMessages.cs(65,32): error CS0115: 'CommandLineValidationMessages.HelpOptionDescription()': no suitable method found to override [/repos/tarball3/src/sdk.af3b7d0f15282afee493e61c10b0bb170317de8d/artifacts/source-build/self/src/src/Cli/dotnet/dotnet.csproj]
  /repos/tarball3/src/sdk.af3b7d0f15282afee493e61c10b0bb170317de8d/artifacts/source-build/self/src/src/Cli/dotnet/Parser.cs(201,34): error CS0115: 'Parser.DotnetHelpBuilder.Write(ICommand, TextWriter, ParseResult)': no suitable method found to override [/repos/tarball3/src/sdk.af3b7d0f15282afee493e61c10b0bb170317de8d/artifacts/source-build/self/src/src/Cli/dotnet/dotnet.csproj]
      0 Warning(s)
      17 Error(s)
```

To resolve this, I think it is a simple matter of updating the Version.Details.xml to reference the sha for 2.0.0-beta1.21504.1.

This was caught in https://github.com/dotnet/installer/pull/12613.

**Comment by MichaelSimons** [comment]
cc @sfoslund - this is blocking source-build.

cc @mmitche

**Comment by sfoslund** [comment]
@MichaelSimons sorry about that, should be pretty quick to fix, I'll take a look.

**Comment by sfoslund** [comment]
@MichaelSimons is there a simple way to repro this issue in the SDK repo?

**Comment by sfoslund** [comment]
@MichaelSimons where can I get the correct sha associated with the version you need?

**Comment by MichaelSimons** [comment]
> where can I get the correct sha associated with the version you need?

``` console
> darc get-asset --name System.CommandLine --version 2.0.0-beta1.21525.1
Looking up assets with name 'System.CommandLine' and version '2.0.0-beta1.21525.1' in the last 30 days
System.CommandLine @ 2.0.0-beta1.21525.1
Repository:    https://github.com/dotnet/command-line-api
Branch:        main
Commit:        09a24a79ef01a0c70655919ee3c59bb54a8574df
Build Number:  20211025.1
Date Produced: 10/25/2021 11:04 AM
Build Link:    https://dev.azure.com/dnceng/internal/_build/results?buildId=1439343
BAR Build Id:  116110
Released:      False
Channels:
- .NET Libraries
Locations:
- https://dev.azure.com/dnceng/internal/_apis/build/builds/1439343/artifacts (Container)
- https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-libraries/nuget/v3/index.json (NugetFeed)
```

**Comment by sfoslund** [comment]
> you should not find any System.CommandLine entries. Right now you will see several 2.0.0-beta1.21525.1 entries.

@MichaelSimons I'm still seeing system.commandline entries in this file when I update the version/sha. Are there any other tricks I'm missing?

**Comment by MichaelSimons** [comment]
What all did you updated?  It is best to utilize darc to make these changes - e.g. `darc update-dependencies --id 116110`.  It looks like an additional package feed is needed though which I was expecting darc make.  Regardless you will need to add the following to the NuGet.config as well.

`<add key="dotnet-libraries-transport" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-libraries-transport/nuget/v3/index.json" />`

I tried this locally and the System.CommandLine prebuilts went away.

**Comment by sfoslund** [comment]
When I do the same thing there are still System.CommandLine entries in the prebuilt usage file, but with a different version than before:

```
<Usage Id="System.CommandLine" Version="2.0.0-beta1.21473.1" />
<Usage Id="System.CommandLine.DragonFruit" Version="0.3.0-alpha.21473.1" />
<Usage Id="System.CommandLine.Rendering" Version="0.3.0-alpha.21473.1" />
```

**Comment by MichaelSimons** [comment]
@sfoslund, Can you share your changes?  What environment are you building on?  I double checked from a clean environment and I do not see any `System.CommandLine` prebuilts.

**Comment by sfoslund** [comment]
I've made a PR with my changes here: https://github.com/dotnet/sdk/pull/22674, I'm working on a mac

**Comment by sfoslund** [comment]
Fixed by https://github.com/dotnet/sdk/pull/22674
