### PR TITLE
Initialization Stopwatch class

### LINKED ISSUE #4803: [Main]  `SDK` failed during build
[Failing build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2599209&view=logs&j=1d0f2ce7-a8ca-596f-a60f-32004bcd1f4a&t=78a76fa6-5c8e-5f23-aef7-18f3ac1c951f) (internal Microsoft link)

    /vmr/src/sdk/src/Cli/Microsoft.DotNet.Cli.Utils/Command.cs(44,28): error CS8600: Converting null literal or possible null value to non-nullable type. [/vmr/src/sdk/src/Cli/Microsoft.DotNet.Cli.Utils/Microsoft.DotNet.Cli.Utils.csproj::TargetFramework=net10.0]
    /vmr/src/sdk/src/Cli/Microsoft.DotNet.Cli.Utils/Command.cs(81,21): error CS8602: Dereference of a possibly null reference. [/vmr/src/sdk/src/Cli/Microsoft.DotNet.Cli.Utils/Microsoft.DotNet.Cli.Utils.csproj::TargetFramework=net10.0]
        0 Warning(s)
        2 Error(s)

This is a regression caused by https://github.com/dotnet/sdk/pull/45393

### PR DESCRIPTION
**Pull request by Winniexu01**
Fixes https://github.com/dotnet/source-build/issues/4803

This is a regression caused by https://github.com/dotnet/sdk/pull/45393

### CODE REVIEW

**Review by jjonescz — CHANGES_REQUESTED** [review]
I would prefer https://github.com/dotnet/sdk/pull/45411

**Review by ellahathaway — COMMENTED** [review]
> I would prefer https://github.com/dotnet/sdk/pull/45411

Agreed. I think that we address this with the PR linked above.
