### ISSUE TITLE
IIS Express project fails to build with error "Reference to type 'IPEndPoint' claims it  is defined in 'System.Net.Primitives', but it could not be found"

### ISSUE THREAD

**Issue by sujitnayak** [dotnet/sdk#36967]
### Describe the bug
After updating VS to 17.8, IISExpress project fails build with error CS7069

### To Reproduce
1 Enlist to IISExpress project @ https://devdiv.visualstudio.com/DevDiv/_git/IISExpress
2 Open dev cmd prompt.
3 cd src/iisexpresstray from the root of the repo.
4 Build with the CLI: 'msbuild /bl iisexpresstray.csproj"

We see following errors:
<<<<<<<<<<<<
"C:\repo\oob\ie\src\iisexpresstray\iisexpresstray.csproj" (default target) (1) ->
(CoreCompile target) ->
  C:\repo\oob\ie\src\iisexpresstray\IisExpressHelper.cs(556,90): error CS7069: Reference to type 'IPEndPoint' claims it
 is defined in 'System.Net.Primitives', but it could not be found [C:\repo\oob\ie\src\iisexpresstray\iisexpresstray.csproj]
  C:\repo\oob\ie\src\iisexpresstray\IisExpressWorkerProcess.cs(534,86): error CS7069: Reference to type 'IPEndPoint' cl
aims it is defined in 'System.Net.Primitives', but it could not be found [C:\repo\oob\ie\src\iisexpresstray\iisexpresstray.csproj]
>>>>>>>>>

### Further technical details

IISExpressTray.csproj targets .NET FX 4.5.2.
VS version: 17.8.0
msbuild version: MSBuild version 17.8.3+195e7f5a3 for .NET Framework 17.8.3.51904

**Comment by sujitnayak** [comment]
The System.Net.Primitives installed in 4.5.2 facades folder (C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades) is missing the IPEndPoint forwarder.

**Comment by sujitnayak** [comment]
The difference b/w the working (17.7) and broken build (17.8) is that in the broken case, the ImplicitlyExpandDesignTimeFacades property is being set to true. This causes the facade DLLs to be included in the references passed to csc which results in the given build error.

**Comment by sujitnayak** [comment]
Closing this issue as this was due to some IISExpress build references having a invalid path in the csproj and the build resolved it to some other locations like the GAC. This caused System.Runtime to get referenced which inturn caused all the Facade DLLs to get referenced.
