### ISSUE TITLE
`dotnet publish` breaking change between 10.0.101 and 10.0.2xx/10.0.3xx: `Program does not contain a static 'Main' method`

### ISSUE THREAD

**Issue by eduherminio** [dotnet/sdk#54841]
### Describe the bug

I can no longer use the following command to publish an executable in [my repo](https://github.com/lynx-chess/Lynx) when using .NET 10.0.301:

```
> dotnet publish src/Lynx.Cli/Lynx.Cli.csproj -o .

CSC : error CS5001: Program does not contain a static 'Main' method suitable for an entry point
```

### Steps to reproduce

```bash
# Works
docker run -it mcr.microsoft.com/dotnet/sdk:10.0.101
git clone https://github.com/lynx-chess/Lynx
cd Lynx/
dotnet publish src/Lynx.Cli/Lynx.Cli.csproj -o .

# Fails
docker run -it mcr.microsoft.com/dotnet/sdk:10.0.201
git clone https://github.com/lynx-chess/Lynx
cd Lynx/
dotnet publish src/Lynx.Cli/Lynx.Cli.csproj -o .

# Fails
docker run -it mcr.microsoft.com/dotnet/sdk:10.0
git clone https://github.com/lynx-chess/Lynx
cd Lynx/
dotnet publish src/Lynx.Cli/Lynx.Cli.csproj -o .
```

Reproduced and originally detected in W11 too.

### Expected behavior

```
 publish src/Lynx.Cli/Lynx.Cli.csproj -o .
Restore complete (3.0s)
  Lynx net10.0 succeeded (6.1s) → src/Lynx/bin/Release/net10.0/Lynx.dll
  Lynx.Cli net10.0 succeeded (0.3s) →

Build succeeded in 9.7s
```

### Actual behavior

```bash
dotnet publish src/Lynx.Cli/Lynx.Cli.csproj -o .
Restore complete (3.3s)
  Lynx net10.0 succeeded (3.4s) → src/Lynx/bin/Release/net10.0/Lynx.dll
  Lynx.Cli net10.0 failed with 1 error(s) (0.2s)
    CSC : error CS5001: Program does not contain a static 'Main' method suitable for an entry point

Build failed with 1 error(s) in 7.0s
```

### Is this a regression?

Yes, working in 10.0.101, broken in 10.0.2xx and 10.0.3xx

### dotnet --info output

```console
.NET SDK:
 Version:           10.0.301
 Commit:            96856fd726
 Workload version:  10.0.300-manifests.b0c14421
 MSBuild version:   18.6.4+96856fd72

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  24.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/10.0.301/
```

**Comment by jjonescz** [comment]
Looks like a duplicate of https://github.com/dotnet/sdk/issues/53626.

**Comment by marcpopMSFT** [comment]
That's fixed in 10.0.4xx previews. Since it's too late for the July release, and 10.0.400 is scheduled for August, that'll be when the fix is released.
