### ISSUE TITLE
Broken build in version 7.0.200

### ISSUE THREAD

**Issue by rholek** [dotnet/sdk#30623]
This code doesn't build with SDK 7.0.200

```
public class C
{
    public async Task M()
    {

        bool shoudRunAgain;

        async Task DoSomething()
        {
            Console.WriteLine("Test");
            shoudRunAgain = false;
        }

        await DoSomething();
        if (shoudRunAgain)
            await DoSomething();
    }
}
```

It fails with error
`
error CS0165: Use of unassigned local variable 'shoudRunAgain'
`

However with version 7.0.102 it builds without error

**Comment by baronfel** [comment]
This looks like new/fixed analyzers were included in 7.0.200, which is not a breaking change per se.

**Comment by baronfel** [comment]
@jaredpar should this go to Roslyn?

**Comment by jaredpar** [comment]
Correct. This is a duplicate of https://github.com/dotnet/roslyn/issues/43697. This was a bug we decided to fix in 7.0 SDK.

**Comment by rholek** [comment]
I must say that I don't see a way this could run without shoudRunAgain being assigned since DoSomething is awaited. But I guess the analysis would be too complicated with that, so I understand.

However, this should be listed as a breaking change.
