### ISSUE TITLE
build.cmd the dotnet/sdk Something went wrong

### ISSUE THREAD

**Issue by tangyanzhi** [dotnet/sdk#33819]
I built dotnet/sdk via build.cmd, but something went wrong, the error is as follows:

```
Build FAILED.

G:\sdk-main\sdk\src\Tests\Microsoft.NET.Publish.Tests\GivenThatWeWantToPublishAFrameworkDependentApp.cs(125,103): error
 CS1056: Unexpected character '\' [G:\sdk-main\sdk\src\Tests\Microsoft.NET.Publish.Tests\Microsoft.NET.Publish.Tests.cs
proj]
G:\sdk-main\sdk\src\Tests\Microsoft.NET.Publish.Tests\GivenThatWeWantToPublishAFrameworkDependentApp.cs(125,104): error
 CS1003: Syntax error, ',' expected [G:\sdk-main\sdk\src\Tests\Microsoft.NET.Publish.Tests\Microsoft.NET.Publish.Tests.
csproj]
G:\sdk-main\sdk\src\Tests\Microsoft.NET.Publish.Tests\GivenThatWeWantToPublishAFrameworkDependentApp.cs(125,121): error
 CS1056: Unexpected character '\' [G:\sdk-main\sdk\src\Tests\Microsoft.NET.Publish.Tests\Microsoft.NET.Publish.Tests.cs
proj]
G:\sdk-main\sdk\src\Tests\Microsoft.NET.Publish.Tests\GivenThatWeWantToPublishAFrameworkDependentApp.cs(125,122): error
 CS1003: Syntax error, ',' expected [G:\sdk-main\sdk\src\Tests\Microsoft.NET.Publish.Tests\Microsoft.NET.Publish.Tests.
csproj]
    0 Warning(s)
    4 Error(s)

Time Elapsed 00:00:56.76
Build failed with exit code 1. Check errors above.
```

How can I fix this error?

**Comment by joeloff** [comment]
Have you been able to build successfully? This could have been a bad merge and transient issue.
