### ISSUE TITLE
Satellite assembly build fails when using Microsoft.Net.Compilers package

### ISSUE THREAD

**Issue by tmat** [dotnet/sdk#1447]
Adding package Microsoft.Net.Compilers to a project with localized resources and compiling with ```dotnet build``` results in build errors such as:

```
D:\symreader-converter\artifacts\Debug\obj\Microsoft.DiaSymReader.Converter\netstandard1.3\cs\Microsoft.DiaSymReader.Converter.resources.cs(10,30): error CS0433: The type 'AssemblyCompanyAttribute' exists in both 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' and 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [D:\symreader-converter\src\Microsoft.DiaSymReader.Converter\Microsoft.DiaSymReader.Converter.csproj]
```

This is caused by NoStdLib and NoConfig arguments missing from the call to the ```csc``` task that compiles satellite assemblies.

**Comment by tmat** [comment]
@nguerrera

**Comment by nguerrera** [comment]
Just to add some detail: using Microsoft.Net.Compilers redirects Csc to a desktop csc.exe delivered by the package. The coreclr csc does not add references implicitly in the absence of /noconfig /nostdlib, but the desktop compiler does. This is why the default case of CoreCLR csc.exe for CLI builds does not hit this.

**Comment by nguerrera** [comment]
@livarcocc Would it be possible to take this in 2.0? The fix is very small and low risk.

**Comment by nguerrera** [comment]
After offline discussion, the bar is now too high to take this in 2.0. This has always existed since 1.0. I will work on getting the 2.1 CLI up-to-date (there's some RI lag, and a bug blocking runtime ingestion). I'll check in the fix to 2.1 and @tmat, I'll let you know when there's a 2.1 preview build with the fix you can use.

**Comment by tmat** [comment]
@nguerrera Sounds good.

**Comment by nguerrera** [comment]
Fixed by #1629, which will flow into 15.5 .NET Core SDK soon.
