### ISSUE TITLE
A part of lambda improvements feature doesn't work with latest SDK 6.0.101

### ISSUE THREAD

**Issue by acple** [dotnet/sdk#23074]
### Describe the bug
Below code is no longer compiled with latest SDK 6.0.101.

```csharp
Enumerable.Range(0, 0).Select(_ => (int x, int y) => x + y);
```
message:
```
error CS0411: The type arguments for method 'Enumerable.Select<TSource, TResult>(IEnumerable<TSource>, Func<TSource, int, TResult>)' cannot be inferred from the usage. Try specifying the type arguments explicitly. [/test/Test.csproj]
```

### To Reproduce
Build the C#10 project with above code on .NET 6.0 SDK 6.0.101.
This could be compiled on .NET 6.0 SDK 6.0.100.

### Further technical details
Environment:
* Docker image:  mcr.microsoft.com/dotnet/sdk:6.0.101-alpine3.14
* dotnet --info (in docker)
```
#8 [4/5] RUN dotnet --info
#8 sha256:d0c665ccd8313952f0043f3c178130f9867385a5390cbed239e4af724429a7da
#8 0.448 .NET SDK (reflecting any global.json):
#8 0.448  Version:   6.0.101
#8 0.448  Commit:    ef49f6213a
#8 0.448
#8 0.448 Runtime Environment:
#8 0.450  OS Name:     alpine
#8 0.450  OS Version:  3.14
#8 0.452  OS Platform: Linux
#8 0.479  RID:         alpine.3.14-x64
#8 0.479  Base Path:   /usr/share/dotnet/sdk/6.0.101/
#8 0.481
#8 0.486 Host (useful for support):
#8 0.486   Version: 6.0.1
#8 0.486   Commit:  3a25a7f1cc
#8 0.486
#8 0.486 .NET SDKs installed:
#8 0.486   6.0.101 [/usr/share/dotnet/sdk]
#8 0.486
#8 0.486 .NET runtimes installed:
#8 0.486   Microsoft.AspNetCore.App 6.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
#8 0.486   Microsoft.NETCore.App 6.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
#8 0.486
#8 0.486 To install additional .NET runtimes or SDKs:
#8 0.486   https://aka.ms/dotnet-download
#8 DONE 0.5s
```

**Comment by KalleOlaviNiemitalo** [comment]
Does this code depend on the <https://github.com/dotnet/csharplang/discussions/150> feature? AFAIK that proposal has not been approved.

**Comment by acple** [comment]
This was introduced in C# 10. https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/lambda-improvements
And it was working fine with previous SDK.

**Comment by KalleOlaviNiemitalo** [comment]
May have been caused by <https://github.com/dotnet/roslyn/pull/57713> in which case this would be a deliberate change.

**Comment by acple** [comment]
Is this a breaking-change as intended? I'd like to know more information about this changes.

**Comment by wegylexy** [comment]
I have a project that builds fine on Windows with the latest VS2022 Preview, but gets type inference issue when built on alpine with the `sdk:6.0-alpine` docker image. I need to specify the type explicitly and suppress the IDE0001 warning so it will stop suggesting me to simplify the name.
