### PR TITLE
NuGet patch to fix obsolete warnings

### LINKED ISSUE #4495: VMR Stage 2 Builds Failing in Nuget Client with Obsolete Reference
See https://github.com/dotnet/source-build/issues/4494. Similar error now appearing in nuget-client.

While testing the changes in https://github.com/dotnet/arcade/pull/14919, a new error appeared in the [stage 2 build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2490784&view=logs&j=3121c41d-6088-53a5-4ef6-9a86f3460fe9&t=334539f4-dcef-5cad-a240-02997b3146e7):

`
/vmr/src/nuget-client/src/NuGet.Core/NuGet.Configuration/Settings/Items/FileClientCertItem.cs(170,66): error SYSLIB0057: 'X509Certificate2.X509Certificate2(string)' is obsolete: 'Loading certificate data through the constructor or Import is obsolete. Use X509CertificateLoader instead to load certificates.' (https://aka.ms/dotnet-warnings/SYSLIB0057) [/vmr/src/nuget-client/src/NuGet.Core/NuGet.Configuration/NuGet.Configuration.csproj]
`

This error is caused by https://github.com/dotnet/runtime/pull/104165.

### PR DESCRIPTION
**Pull request by ellahathaway**
Fixes https://github.com/dotnet/source-build/issues/4495

Filed https://github.com/NuGet/Home/issues/13612 as the backport issue.

[Test build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2491671&view=results) (internal Microsoft link)

Will publish once test build completes.

### CODE REVIEW

**Comment by akoeplinger** [comment]
This needed a couple more fixes, I opened https://github.com/dotnet/sdk/pull/42065 and a corresponding upstream PR.
